INSERT INTO SPEISSE VALUES (1,'Schnitzel',12, 1, TRUE);
INSERT INTO SPEISSE VALUES (2,'Gulasch',9, 1, FALSE);
INSERT INTO SPEISSE VALUES (3,'Pizza',10, 1, FALSE);
INSERT INTO SPEISSE VALUES (4,'Burger',9, 1, FALSE);

INSERT INTO GETRAENK VALUES (1,'Sprite',3.5, TRUE, 0.5);
INSERT INTO GETRAENK VALUES (2,'Cola',3.5, TRUE, 0.5);
INSERT INTO GETRAENK VALUES (3,'Apfelsaft',3, FALSE, 0.5);
INSERT INTO GETRAENK VALUES (4,'Almdudler',3.5, TRUE, 0.5);

INSERT INTO MITARBEITER VALUES (1,18,'Sarah','Feichtinger',1);
INSERT INTO MITARBEITER VALUES (2,17,'Marah','Steigersdorfer',2);

INSERT INTO KUNDE VALUES (1,55,'Ben','Stiller');
INSERT INTO KUNDE VALUES (2,83,'Morgan','Freeman');
INSERT INTO KUNDE VALUES (3,55,'Robert','Downey Jr.');
INSERT INTO KUNDE VALUES (4,54,'Adam','Sandler');

INSERT INTO TISCH VALUES (1,8);
INSERT INTO TISCH VALUES (2,4);
INSERT INTO TISCH VALUES (3,4);
INSERT INTO TISCH VALUES (4,2);

INSERT INTO RESERVIERUNG VALUES (1,1);
INSERT INTO RESERVIERUNG VALUES (2,2);
INSERT INTO RESERVIERUNG VALUES (3,3);
INSERT INTO RESERVIERUNG VALUES (4,4);

INSERT INTO BESTELLUNG VALUES (1,1,1);
INSERT INTO BESTELLUNG VALUES (2,2,2);
INSERT INTO BESTELLUNG VALUES (3,2,3);
INSERT INTO BESTELLUNG VALUES (4,1,4);


INSERT INTO BESTELLLISTE VALUES (1,1,1, 1);
INSERT INTO BESTELLLISTE VALUES (2,2,1, 1);
INSERT INTO BESTELLLISTE VALUES (3,3,1, 1);
INSERT INTO BESTELLLISTE VALUES (4,1,1, 1);
INSERT INTO BESTELLLISTE VALUES (5,4,1, 1);
INSERT INTO BESTELLLISTE VALUES (6,3,1, 1);
INSERT INTO BESTELLLISTE VALUES (7,1,1, 1);

INSERT INTO BESTELLLISTE VALUES (8,1,2,2);
INSERT INTO BESTELLLISTE VALUES (9,2,2,2);
INSERT INTO BESTELLLISTE VALUES (10,3,2,2);
INSERT INTO BESTELLLISTE VALUES (11,1,2,2);

INSERT INTO BESTELLLISTE VALUES (12,4,3,2);
INSERT INTO BESTELLLISTE VALUES (13,3,3,2);
INSERT INTO BESTELLLISTE VALUES (14,1,3,2);
INSERT INTO BESTELLLISTE VALUES (15,4,3,2);

INSERT INTO BESTELLLISTE VALUES (16,1,4,1);
INSERT INTO BESTELLLISTE VALUES (17,4,4,1);
